import { defineConfig } from 'vite';
import laravel from 'laravel-vite-plugin';

export default defineConfig({
    plugins: [
        laravel({
            input: [
                'resources/sass/app.scss',
                'resources/js/app.js',
                'resources/assets/vendor/libs/apex-charts/apex-charts.scss',
                'resources/assets/vendor/libs/swiper/swiper.scss',
                'resources/assets/vendor/scss/pages/cards-statistics.scss',
                'resources/assets/vendor/scss/pages/cards-analytics.scss',
                'resources/assets/vendor/fonts/remixicon/remixicon.scss',
                'resources/assets/vendor/fonts/flag-icons.scss',
                'resources/assets/vendor/libs/node-waves/node-waves.scss',
                'resources/assets/vendor/scss/rtl/core.scss',
                'resources/assets/vendor/scss/rtl/theme-default.scss',
                'resources/assets/css/demo.css',
                'resources/assets/vendor/libs/perfect-scrollbar/perfect-scrollbar.scss',
                'resources/assets/vendor/libs/typeahead-js/typeahead.scss',
                'resources/assets/vendor/scss/rtl/core-dark.scss',
                'resources/assets/vendor/scss/rtl/theme-default-dark.scss',
                'resources/assets/vendor/scss/rtl/theme-bordered.scss',
                'resources/assets/vendor/scss/rtl/theme-bordered-dark.scss',
                'resources/assets/vendor/scss/rtl/theme-semi-dark.scss',
                'resources/assets/vendor/scss/rtl/theme-semi-dark-dark.scss',
                'resources/assets/vendor/libs/flatpickr/flatpickr.scss',
                'resources/assets/vendor/libs/select2/select2.scss',
                'resources/assets/vendor/libs/datatables-bs5/datatables.bootstrap5.scss',
                'resources/assets/vendor/libs/datatables-responsive-bs5/responsive.bootstrap5.scss',
                'resources/assets/vendor/libs/datatables-buttons-bs5/buttons.bootstrap5.scss',
                'resources/assets/vendor/libs/@form-validation/form-validation.scss',
                'resources/assets/vendor/libs/animate-css/animate.scss',
                'resources/assets/vendor/libs/sweetalert2/sweetalert2.scss',
                'resources/assets/vendor/libs/moment/moment.js',
                'resources/assets/vendor/libs/datatables-bs5/datatables-bootstrap5.js',
                'resources/assets/vendor/libs/select2/select2.js',
                'resources/assets/vendor/libs/@form-validation/popular.js',
                'resources/assets/vendor/libs/@form-validation/bootstrap5.js',
                'resources/assets/vendor/libs/@form-validation/auto-focus.js',
                'resources/assets/vendor/libs/cleavejs/cleave.js',
                'resources/assets/vendor/libs/cleavejs/cleave-phone.js',
                'resources/assets/vendor/libs/sweetalert2/sweetalert2.js',
                'resources/assets/vendor/js/helpers.js',
                'resources/assets/vendor/js/template-customizer.js',
                'resources/assets/js/config.js',
                'resources/assets/vendor/libs/popper/popper.js',
                'resources/assets/vendor/libs/node-waves/node-waves.js',
                'resources/assets/vendor/libs/perfect-scrollbar/perfect-scrollbar.js',
                'resources/assets/vendor/libs/hammer/hammer.js',
                'resources/assets/vendor/libs/typeahead-js/typeahead.js',
                'resources/assets/vendor/js/menu.js',
                'resources/assets/vendor/libs/jquery/jquery.js',
                'resources/assets/vendor/js/bootstrap.js',
                'resources/assets/js/main.js',
                'resources/assets/vendor/libs/flatpickr/flatpickr.js',
                'resources/assets/js/form-layouts.js',
                'resources/js/users.js',
                'resources/js/payments.js',
                'resources/assets/vendor/libs/apex-charts/apexcharts.js',
                'resources/assets/vendor/libs/jquery/jquery.js',

                'resources/assets/vendor/libs/swiper/swiper.js',
                'resources/assets/vendor/libs/moment/moment.js',
                'resources/assets/vendor/js/bootstrap.js',
                'resources/assets/js/dashboards-analytics.js',
                'resources/assets/js/main.js',
                'resources/js/courses.js',
                'resources/js/subscribers.js',
                'resources/assets/js/form-layouts.js',
                'resources/assets/js/pages-auth.js'
                
                
                
                
            ],
            refresh: true,
        }),
    ],
    build: {
        
        chunkSizeWarningLimit: 5000,
    },
});
